oracle.net.tns_admin=C:/Users/maria/Downloads/SGBD/schemaspy/wallet
javax.net.ssl.trustStore=C:/Users/maria/Downloads/SGBD/schemaspyy/wallet/truststore.jks
javax.net.ssl.trustStorePassword=Cazafantasmas32@
javax.net.ssl.keyStore=C:/Users/maria/Downloads/SGBD/schemaspy/wallet/keystore.jks
javax.net.ssl.keyStorePassword=Cazafantasmas32@
oracle.net.ssl_server_dn_match=true
oracle.net.ssl_version=1.2