# Custom SchemaSpy dbType for Oracle Autonomous DB using Thin + Wallet (TNS alias)
extends=ora
connectionSpec=jdbc:oracle:thin:@<db>?TNS_ADMIN=C:/Users/maria/Downloads/SGBD/schemaspy/schemaspy/wallet
db=database name (TNS alias from tnsnames.ora)

